# tasks file
---
- name: repository | install | dependencies (pre)
  apt:
    name: "{{ virtualbox_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - virtualbox-repository-install
    - virtualbox-repository-install-dependencies

- name: repository | add public key
  apt_key:
    id: "{{ item.id }}"
    url: "{{ item.url }}"
    state: present
  with_items: "{{ virtualbox_public_keys }}"
  tags:
    - virtualbox-repository-public-key

- name: repository | add repository
  apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
    mode: 0644
  with_items: "{{ virtualbox_repositories }}"
  tags:
    - virtualbox-repository-add
